[phases.setup]
aptPkgs = ["build-essential", "libpq-dev"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python src/main.py"

